version: '3.8'

services:
  admin:
    build:
      context: ./smartparking
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}:smartparking"
    environment:
      - ENVIRONMENT=dev
    ports:
      - "${ADMIN_PORT}:8000"
    depends_on:
      - db
    command: /home/QrParking/smartparking/shell/dev_entrypoint.sh
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}:api"
    ports:
      - "${API_PORT}:8001"
    environment:
      - ENVIRONMENT=dev
    volumes:
      - "./api:/home/QrParking/api"
    depends_on:
      - db
    command: >
      sh -c "uvicorn smartparking.main:app --host 0.0.0.0 --port 8001"
    restart: always





