version: '3.8'

services:
  web:
    build:
      context: ./smartparking
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}:smartparking"
    environment:
      - ENVIRONMENT=dev
    ports:
      - "${ADMIN_PORT}:8000"
    volumes:
      - ./smartparking/staticfiles:/home/QrParking/smartparking/staticfiles:rw
    depends_on:
      - db
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput --no-post-process &&
        chmod -R u+w /home/QrParking/smartparking/staticfiles &&
        python create_superuser_and_site.py &&
        python manage.py runserver 0.0.0.0:8000
      "
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}:api"
    ports:
      - "${API_PORT}:8001"
    environment:
      - ENVIRONMENT=dev
    volumes:
      - "./api:/home/QrParking/api"
    depends_on:
      - db
    command: >
      sh -c "uvicorn smartparking.main:app --host 0.0.0.0 --port 8001"
    restart: always





