version: '3.8'

services:
  web:
    build:
      context: ./smartparking
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}:smartparking"
    environment:
      - ENVIRONMENT=dev
    ports:
      - "${ADMIN_PORT}:8000"
    depends_on:
      - db
    networks:
      - qrparking_network
    volumes:
      - "./smartparking:/home/QrParking/smartparking"
      - "./smartparking/staticfiles:/home/QrParking/smartparking/staticfiles"
      - "./smartparking/shell:/home/QrParking/smartparking/shell"
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}:api"
    environment:
      - ENVIRONMENT=dev
    ports:
      - "${API_PORT}:8001"
    depends_on:
      - db
      - mqtt
    networks:
      - qrparking_network
    restart: always

  db:
    image: postgres:15.1-alpine
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/${PROJECT_NAME}"
      POSTGRES_DB: "${DB_NAME}"
    networks:
      - qrparking_network
    volumes:
      - "db_volume:/var/lib/postgresql/data/${PROJECT_NAME}"
      - "./db/initdb.d/create-db.sh:/docker-entrypoint-initdb.d/create-db.sh"
    restart: always

  db_stg:
    image: postgres:15.1-alpine
    env_file:
      - ./.env
    ports:
      - "${DB_PORT_STG}:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/${PROJECT_NAME}_stg"
      POSTGRES_DB: "${DB_NAME}_stg"
    networks:
      - qrparking_network
    volumes:
      - "db_stg_volume:/var/lib/postgresql/data/${PROJECT_NAME}_stg"
      - "./db/initdb.d/create-db.sh:/docker-entrypoint-initdb.d/create-db.sh"
    restart: always

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9002:9002"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    command: >
      /bin/sh -c "
      if [ ! -f /mosquitto/config/password.txt ]; then 
        mosquitto_passwd -c -b /mosquitto/config/password.txt ${MQTT_USERNAME} ${MQTT_PASSWORD}; 
        chmod 0700 /mosquitto/config/password.txt; 
        chown root:root /mosquitto/config/password.txt; 
      fi && mosquitto -c /mosquitto/config/mosquitto.conf"
    networks:
      - qrparking_network
    restart: always

networks:
  qrparking_network:
    driver: bridge

volumes:
  db_volume:
  db_stg_volume:
